- id: '1588641681519'
  alias: Printer Ink Notification
  description: ''
  trigger:
  - below: 15
    device_id: 8f8604b75c4c46499aa8a10fab88613c
    domain: sensor
    entity_id: sensor.epson_xp_442_445_series_black_ink
    platform: device
    type: value
  - below: 15
    device_id: 8f8604b75c4c46499aa8a10fab88613c
    domain: sensor
    entity_id: sensor.epson_xp_442_445_series_cyan_ink
    platform: device
    type: value
  - below: 15
    device_id: 8f8604b75c4c46499aa8a10fab88613c
    domain: sensor
    entity_id: sensor.epson_xp_442_445_series_magenta_ink
    platform: device
    type: value
  - below: 15
    device_id: 8f8604b75c4c46499aa8a10fab88613c
    domain: sensor
    entity_id: sensor.epson_xp_442_445_series_yellow_ink
    platform: device
    type: value
  condition: []
  action:
  - data:
      message: Printer Ink is low
    service: notify.telegram
- id: '1589679315386'
  alias: Toggle Fish Light
  description: Toggle the Fish Light at 6am and 8pm
  trigger:
  - at: 06:00:00
    platform: time
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - type: toggle
    device_id: 63db3e4116d9466d8d0452edb7ab7325
    entity_id: switch.fishlight
    domain: switch
  - data:
      message: The Fish Light has been toggled
    service: notify.telegram
  mode: single
- id: '1602319276462'
  alias: Update Countdowns
  description: ''
  trigger:
  - at: 00:01:00
    platform: time
  condition: []
  action:
  - data: {}
    service: python_script.registration_countdown
  - service: python_script.bin_collection
    data: {}
  mode: single
- id: '1606477656688'
  alias: Notification for Update Available
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g975f
    data:
      title:
      message: There is a HA Update available, check the release notes, and install
  mode: single
